services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=picpaydb
      - MYSQL_ROOT_PASSWORD=root
volumes:
  db_data: